### ISSUE TITLE
[🚀] HTTPS support for REST integration

### ISSUE THREAD

**Issue by finnWellers** [jeakfrw/jeak-framework#59]
**Describe the solution you'd like**
The REST integration should be able to serve the API using HTTPS for obvious security reasons.  
Controllers should be able to check whether or not a connection is encrypted.

**Describe why you would like to see this implemented**
This allows controllers that would provider sensitive data to outright reject the request due to a lack of encryption. Of course it would include serving requests over HTTPS.

**Comment by MarkTwoFive** [comment]
@finnWellers do you think the encryption enforcement should be something that could be configured by the endpoint annotation? Something like ``forceEncrypted`` or ``rejectUnencrypted``?

**Comment by finnWellers** [comment]
That sounds like an interesting idea. It only depends on how we are going to implement HTTPS. When using an NGINX as reverse proxy, the application only knows HTTP.

**Comment by MarkTwoFive** [comment]
I would say that does not depend on that. For both the reverse proxy and the HTTPS capable setup we can know whether or not a HTTPS connection is in use. For reverse proxy-setups, the convention is to set the ``X-Forwarded-Proto`` header to ``https`` in the reverse proxy request.

**Comment by MarkTwoFive** [comment]
For example, Jenkins and Nexus are also consuming this header and switch to https resource URLs when the header is set.

**Comment by finnWellers** [comment]
What do you think, should https be enforced by default or not?
