### ISSUE TITLE
[🚀] add "deprecated" commands

### ISSUE THREAD

**Issue by timgurke** [jeakfrw/jeak-framework#76]
Add "deprecated" commands that continue to execute the command, but also notify the user that the command has been replaced, modified, or removed.

This makes it easier to modify or remove existing commands across multiple releases.

**Comment by MarkTwoFive** [comment]
Great idea 👍   
This will be especially useful for the introduction of the planned new command service.

**Comment by MarkTwoFive** [comment]
This has been merged in #82
