### ISSUE TITLE
[🚧] [REST-Svc] Strange behaviour under (slight) load

### ISSUE THREAD

**Issue by finnWellers** [jeakfrw/jeak-framework#80]
Collect here Information on the behaviour.

**Comment by finnWellers** [comment]
* While the Framework is busy with some other task (e.g. refreshing the clients), the rest-service can`t handle requests. 
* another task seems to interrupt the webserver and after this it doesnt answer requests it got (not allways. But the EventService might break something there)
* The logging takes a bit of time
* After reaching 100% cpu load, the cpu load gets reduced to 0% for about 10 seconds

For one user, the query http://bradd.fearnixx.de:8723/api/testPluginId/test/info\?name\=finn takes 55-65 ms (until 1800 samples, after this the clients were refreshed and no further requests were answered for 2 minutes)

**Comment by MarkTwoFive** [comment]
I can't stress the ___very___ in "very strange" enough :sweat_smile: judging by your observation...  
In absolutely no way should the event service, query connection or cache interfer with the web server. The only thing cross-blocking threads there is the synchronized getter calls which will block while a new response is parsed.... this takes less than a second or two even on just the one CPU core ._.

**Comment by finnWellers** [comment]
It appears that the UserService made requests to Teamspeak (useing the QueryUserService). Using the DBUserService improves the situation.

**Comment by finnWellers** [comment]
Fixed by #101
